language: python
python:
  - "3.6"
  - "nightly"
install:
  - "pip install pytest"
  - "pip install -r Pythontests/starter_code_REST_pt2/requirements.txt"
script: python -m pytest Pythontests/starter_code_REST_pt2/tests/